# import Modulus

In [39]:
import pandas as pd
import numpy as np
import seaborn as sns
import re
import nltk
pd.set_option('display.max_columns', None)

# Load the dataset

In [40]:
df = pd.read_csv("IMDB_Top250Engmovies2_OMDB_Detailed.csv")
df.head(2)

Unnamed: 0                     Title  Year Rated     Released  Runtime  \
0           1  The Shawshank Redemption  1994     R  14 Oct 1994  142 min   
1           2             The Godfather  1972     R  24 Mar 1972  175 min   

          Genre              Director  \
0  Crime, Drama        Frank Darabont   
1  Crime, Drama  Francis Ford Coppola   

                                              Writer  \
0  Stephen King (short story "Rita Hayworth and S...   
1  Mario Puzo (screenplay), Francis Ford Coppola ...   

                                              Actors  \
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...   
1  Marlon Brando, Al Pacino, James Caan, Richard ...   

                                                Plot                 Language  \
0  Two imprisoned men bond over a number of years...                  English   
1  The aging patriarch of an organized crime dyna...  English, Italian, Latin   

  Country                                             Awards  \
0     USA  Nominated for 7 Oscars. Another 19 wins & 30 n...   
1     USA    Won 3 Oscars. Another 23 wins & 27 nominations.   

                                              Poster           Ratings.Source  \
0  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   
1  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   

  Ratings.Value  Metascore  imdbRating  imdbVotes     imdbID   Type  \
0        9.3/10       80.0         9.3  1,825,626  tt0111161  movie   
1        9.2/10      100.0         9.2  1,243,444  tt0068646  movie   

   tomatoMeter  tomatoImage  tomatoRating  tomatoReviews  tomatoFresh  \
0          NaN          NaN           NaN            NaN          NaN   
1          NaN          NaN           NaN            NaN          NaN   

   tomatoRotten  tomatoConsensus  tomatoUserMeter  tomatoUserRating  \
0           NaN              NaN              NaN               NaN   
1           NaN              NaN              NaN               NaN   

   tomatoUserReviews                                          tomatoURL  \
0                NaN  http://www.rottentomatoes.com/m/shawshank_rede...   
1                NaN         http://www.rottentomatoes.com/m/godfather/   

           DVD BoxOffice          Production                      Website  \
0  27 Jan 1998       NaN   Columbia Pictures                          NaN   
1  09 Oct 2001       NaN  Paramount Pictures  http://www.thegodfather.com   

   Response  
0      True  
1      True

In [41]:
len(df)

250

In [42]:
df['Plot'][0]

'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.'

# Data Preprocessing

In [43]:
# Convert lower case and remove numbers, punctutations,spaces,etc.

df['clean_plot'] = df['Plot'].str.lower()
df['clean_plot'] = df['clean_plot'].apply(lambda x: re.sub('[^a-zA-Z]', ' ', x))
df['clean_plot'] = df['clean_plot'].apply(lambda x: re.sub('\s+', ' ', x))
df['clean_plot']

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
C:\Users\harip\AppData\Local\Temp\ipykernel_6260\2698208319.py:5: SyntaxWarning: invalid escape sequence '\s'
  df['clean_plot'] = df['clean_plot'].apply(lambda x: re.sub('\s+', ' ', x))


0      two imprisoned men bond over a number of years...
1      the aging patriarch of an organized crime dyna...
2      the early life and career of vito corleone in ...
3      when the menace known as the joker emerges fro...
4      a jury holdout attempts to prevent a miscarria...
                             ...                        
245    the desperate life of a chronic alcoholic is f...
246    a something supervising staff member of a resi...
247    a newspaper editor uses every trick in the boo...
248    an old man makes a long journey by lawn mover ...
249    a mumbai teen reflects on his upbringing in th...
Name: clean_plot, Length: 250, dtype: object

In [44]:
# Tokenize the sentence

df['clean_plot'] = df['clean_plot'].apply(lambda x: nltk.word_tokenize(x))
df['clean_plot']

0      [two, imprisoned, men, bond, over, a, number, ...
1      [the, aging, patriarch, of, an, organized, cri...
2      [the, early, life, and, career, of, vito, corl...
3      [when, the, menace, known, as, the, joker, eme...
4      [a, jury, holdout, attempts, to, prevent, a, m...
                             ...                        
245    [the, desperate, life, of, a, chronic, alcohol...
246    [a, something, supervising, staff, member, of,...
247    [a, newspaper, editor, uses, every, trick, in,...
248    [an, old, man, makes, a, long, journey, by, la...
249    [a, mumbai, teen, reflects, on, his, upbringin...
Name: clean_plot, Length: 250, dtype: object

In [45]:
# Remove stop words

stop_words = nltk.corpus.stopwords.words('english')
plot = []

for sentence in df['clean_plot']:
    temp = []
    for word in sentence:
        if word not in stop_words or len(word) >= 3:
            temp.append(word)
    plot.append(temp)
plot

[['two',
  'imprisoned',
  'men',
  'bond',
  'over',
  'number',
  'years',
  'finding',
  'solace',
  'and',
  'eventual',
  'redemption',
  'through',
  'acts',
  'common',
  'decency'],
 ['the',
  'aging',
  'patriarch',
  'organized',
  'crime',
  'dynasty',
  'transfers',
  'control',
  'his',
  'clandestine',
  'empire',
  'his',
  'reluctant',
  'son'],
 ['the',
  'early',
  'life',
  'and',
  'career',
  'vito',
  'corleone',
  'new',
  'york',
  'portrayed',
  'while',
  'his',
  'son',
  'michael',
  'expands',
  'and',
  'tightens',
  'his',
  'grip',
  'the',
  'family',
  'crime',
  'syndicate'],
 ['when',
  'the',
  'menace',
  'known',
  'the',
  'joker',
  'emerges',
  'from',
  'his',
  'mysterious',
  'past',
  'wreaks',
  'havoc',
  'and',
  'chaos',
  'the',
  'people',
  'gotham',
  'the',
  'dark',
  'knight',
  'must',
  'accept',
  'one',
  'the',
  'greatest',
  'psychological',
  'and',
  'physical',
  'tests',
  'his',
  'ability',
  'fight',
  'injustice'],

In [46]:
df['clean_plot'] = plot

In [47]:
df['clean_plot']

0      [two, imprisoned, men, bond, over, number, yea...
1      [the, aging, patriarch, organized, crime, dyna...
2      [the, early, life, and, career, vito, corleone...
3      [when, the, menace, known, the, joker, emerges...
4      [jury, holdout, attempts, prevent, miscarriage...
                             ...                        
245    [the, desperate, life, chronic, alcoholic, fol...
246    [something, supervising, staff, member, reside...
247    [newspaper, editor, uses, every, trick, the, b...
248    [old, man, makes, long, journey, lawn, mover, ...
249    [mumbai, teen, reflects, his, upbringing, the,...
Name: clean_plot, Length: 250, dtype: object

In [48]:
df.head()

Unnamed: 0                     Title  Year     Rated     Released  Runtime  \
0           1  The Shawshank Redemption  1994         R  14 Oct 1994  142 min   
1           2             The Godfather  1972         R  24 Mar 1972  175 min   
2           3    The Godfather: Part II  1974         R  20 Dec 1974  202 min   
3           4           The Dark Knight  2008     PG-13  18 Jul 2008  152 min   
4           5              12 Angry Men  1957  APPROVED  01 Apr 1957   96 min   

                  Genre              Director  \
0          Crime, Drama        Frank Darabont   
1          Crime, Drama  Francis Ford Coppola   
2          Crime, Drama  Francis Ford Coppola   
3  Action, Crime, Drama     Christopher Nolan   
4          Crime, Drama          Sidney Lumet   

                                              Writer  \
0  Stephen King (short story "Rita Hayworth and S...   
1  Mario Puzo (screenplay), Francis Ford Coppola ...   
2  Francis Ford Coppola (screenplay), Mario Puzo ...   
3  Jonathan Nolan (screenplay), Christopher Nolan...   
4  Reginald Rose (story), Reginald Rose (screenplay)   

                                              Actors  \
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...   
1  Marlon Brando, Al Pacino, James Caan, Richard ...   
2  Al Pacino, Robert Duvall, Diane Keaton, Robert...   
3  Christian Bale, Heath Ledger, Aaron Eckhart, M...   
4  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....   

                                                Plot  \
0  Two imprisoned men bond over a number of years...   
1  The aging patriarch of an organized crime dyna...   
2  The early life and career of Vito Corleone in ...   
3  When the menace known as the Joker emerges fro...   
4  A jury holdout attempts to prevent a miscarria...   

                                     Language  Country  \
0                                     English      USA   
1                     English, Italian, Latin      USA   
2  English, Italian, Spanish, Latin, Sicilian      USA   
3                           English, Mandarin  USA, UK   
4                                     English      USA   

                                              Awards  \
0  Nominated for 7 Oscars. Another 19 wins & 30 n...   
1    Won 3 Oscars. Another 23 wins & 27 nominations.   
2    Won 6 Oscars. Another 10 wins & 20 nominations.   
3  Won 2 Oscars. Another 151 wins & 153 nominations.   
4  Nominated for 3 Oscars. Another 16 wins & 8 no...   

                                              Poster           Ratings.Source  \
0  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   
1  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   
2  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   
3  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   
4  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   

  Ratings.Value  Metascore  imdbRating  imdbVotes     imdbID   Type  \
0        9.3/10       80.0         9.3  1,825,626  tt0111161  movie   
1        9.2/10      100.0         9.2  1,243,444  tt0068646  movie   
2        9.0/10       85.0         9.0    856,870  tt0071562  movie   
3        9.0/10       82.0         9.0  1,802,351  tt0468569  movie   
4        8.9/10       96.0         8.9    494,215  tt0050083  movie   

   tomatoMeter  tomatoImage  tomatoRating  tomatoReviews  tomatoFresh  \
0          NaN          NaN           NaN            NaN          NaN   
1          NaN          NaN           NaN            NaN          NaN   
2          NaN          NaN           NaN            NaN          NaN   
3          NaN          NaN           NaN            NaN          NaN   
4          NaN          NaN           NaN            NaN          NaN   

   tomatoRotten  tomatoConsensus  tomatoUserMeter  tomatoUserRating  \
0           NaN              NaN              NaN               NaN   
1           NaN              

In [49]:
df['Genre'] = df['Genre'].apply(lambda x: x.split(','))
df['Actors'] = df['Actors'].apply(lambda x: x.split(',')[:4])
df['Director'] = df['Director'].apply(lambda x: x.split(','))

In [50]:
df['Actors'][0]

['Tim Robbins', ' Morgan Freeman', ' Bob Gunton', ' William Sadler']

In [51]:
def clean(sentence):
    temp = []
    for word in sentence:
        temp.append(word.lower().replace(' ',''))
    return temp
        

In [52]:
df['Genre'] = [clean(x) for x in df['Genre']]
df['Actors'] = [clean(x) for x in df['Actors']]
df['Director'] = [clean(x) for x in df['Director']]

In [53]:
df['Actors'][0]

['timrobbins', 'morganfreeman', 'bobgunton', 'williamsadler']

In [54]:
# combining all the columns data

columns = ['clean_plot','Genre','Actors','Director']
l =[]
for i in  range(len(df)):
    words=''
    for col in columns:
        words +=' '.join(df[col][i]) + ' '
    l.append(words)
l
    

['two imprisoned men bond over number years finding solace and eventual redemption through acts common decency crime drama timrobbins morganfreeman bobgunton williamsadler frankdarabont ',
 'the aging patriarch organized crime dynasty transfers control his clandestine empire his reluctant son crime drama marlonbrando alpacino jamescaan richards.castellano francisfordcoppola ',
 'the early life and career vito corleone new york portrayed while his son michael expands and tightens his grip the family crime syndicate crime drama alpacino robertduvall dianekeaton robertdeniro francisfordcoppola ',
 'when the menace known the joker emerges from his mysterious past wreaks havoc and chaos the people gotham the dark knight must accept one the greatest psychological and physical tests his ability fight injustice action crime drama christianbale heathledger aaroneckhart michaelcaine christophernolan ',
 'jury holdout attempts prevent miscarriage justice forcing his colleagues reconsider the evid

In [55]:
df['clean_input'] = l
df = df[['Title','clean_input']]
df.head()

Title                                        clean_input
0  The Shawshank Redemption  two imprisoned men bond over number years find...
1             The Godfather  the aging patriarch organized crime dynasty tr...
2    The Godfather: Part II  the early life and career vito corleone new yo...
3           The Dark Knight  when the menace known the joker emerges from h...
4              12 Angry Men  jury holdout attempts prevent miscarriage just...

# Feature Extraction

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
tfidf = TfidfVectorizer()
features = tfidf.fit_transform(df['clean_input'])

In [57]:
# create cosine similarity matrix
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(features,features)
print(cosine_sim)

[[1.         0.02563307 0.03298711 ... 0.0034532  0.0034371  0.00328715]
 [0.02563307 1.         0.20305027 ... 0.02049564 0.01677256 0.02297934]
 [0.03298711 0.20305027 1.         ... 0.02249223 0.01562757 0.02787553]
 ...
 [0.0034532  0.02049564 0.02249223 ... 1.         0.00998932 0.01633847]
 [0.0034371  0.01677256 0.01562757 ... 0.00998932 1.         0.00950896]
 [0.00328715 0.02297934 0.02787553 ... 0.01633847 0.00950896 1.        ]]


# Movie Recommendation

In [58]:
index = pd.Series(df['Title'])
index.head()

0    The Shawshank Redemption
1               The Godfather
2      The Godfather: Part II
3             The Dark Knight
4                12 Angry Men
Name: Title, dtype: object

In [59]:
def recommend_movies(title):
    movies = []
    idx = index[index == title].index[0]
    print(idx)
    score = pd.Series(cosine_sim[idx]).sort_values(ascending=False)
    top10 = list(score.iloc[1:11].index)
    print(top10)

    for i in top10:
        movies.append(df['Title'][i])
    return movies

In [60]:
recommend_movies('The Dark Knight Rises')

51
[3, 89, 12, 9, 17, 59, 15, 13, 48, 97]


['The Dark Knight',
 'Batman Begins',
 'Inception',
 'The Lord of the Rings: The Fellowship of the Ring',
 'Star Wars: Episode IV - A New Hope',
 'Star Wars: Episode VI - Return of the Jedi',
 'Goodfellas',
 'The Lord of the Rings: The Two Towers',
 'Django Unchained',
 'Die Hard']

In [64]:
index[index == 'The Dark Knight Rises'].index[0]

51

In [65]:
pd.Series(cosine_sim[51]).sort_values(ascending=False)

51     1.000000
3      0.255381
89     0.201010
12     0.157975
9      0.152506
         ...   
62     0.000000
46     0.000000
194    0.000000
44     0.000000
164    0.000000
Length: 250, dtype: float64

In [67]:
recommend_movies('The Godfather: Part II')

2
[1, 15, 165, 175, 94, 49, 71, 115, 134, 172]


['The Godfather',
 'Goodfellas',
 'Spider-Man: Homecoming',
 'Annie Hall',
 'Raging Bull',
 'The Shining',
 'Taxi Driver',
 'The Wolf of Wall Street',
 'There Will Be Blood',
 'Gandhi']

In [68]:
recommend_movies('The Avengers')

219
[203, 199, 222, 55, 25, 108, 3, 6, 190, 136]


['Guardians of the Galaxy Vol. 2',
 'Guardians of the Galaxy',
 'The Martian',
 'Aliens',
 'Interstellar',
 'Blade Runner',
 'The Dark Knight',
 'The Lord of the Rings: The Return of the King',
 'The Terminator',
 'Kill Bill: Vol. 1']

In [69]:
len(df)

250